version: '3'
services:
  server:
    image: agarichan/softether
    container_name: softether-server
    cap_add:
      - NET_ADMIN
    volumes:
      - ./server:/server
    ports:
      - 5432:5432
    restart: always