version: '3'
services:
  server:
    image: agarichan/softether
    container_name: softether-server
    cap_add:
      - NET_ADMIN
    volumes:
      - softether-server:/server
    ports:
      - 5432:5432
    restart: always

volumes:
  softether-server: